name: chat_app_n8n
description: Flutter ChatN8n
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
